# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdeb4fc5a8f08bebbc3e6f61e7d0faaf8a326893cff2dcb54e4a252e09aa7c33ee4c8847cafc163ddd0f134ba819798b403b0ae8a5d28387043a66a38b86e682

test:
  secret_key_base: 6fc6b2c1da7d565d355efebfb44cfe588efef6ed187afd546adf53c949a440269b8b0831a7518ea1867bf3be8d249bfa53ebf498cf19ca9c4425b41367deb57e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
